# SPDX-FileCopyrightText: 2022 jerusdp
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "test-suite-cli"
version = "3.1.1"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
